import requests
import os
import urllib3
from lxml import etree




urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)


SERVICE_LAYER_URL = os.getenv("SERVICE_LAYER_URL")
USER = os.getenv("SERVICE_LAYER_USER")
PASS = os.getenv("SERVICE_LAYER_PASS")

ENTITY_LIST=["AccountCategory",
"AccountSegmentationCategories",
"AccountSegmentations",
"AccrualTypes",
"Activities",
"ActivityLocations",
"ActivityRecipientLists",
"ActivityStatuses",
"ActivityTypes",
"AdditionalExpenses",
"AlertManagements",
"AlternateCatNum",
"ApprovalRequests",
"ApprovalStages",
"ApprovalTemplates",
"AssetCapitalization",
"AssetCapitalizationCreditMemo",
"AssetClasses",
"AssetDepreciationGroups",
"AssetGroups",
"AssetManualDepreciation",
"AssetRetirement",
"AssetTransfer",
"Attachments2",
"AttributeGroups",
"BankChargesAllocationCodes",
"BankPages",
"Banks",
"BankStatements",
"BarCodes",
"BatchNumberDetails",
"BEMReplicationPeriods",
"BillOfExchangeTransactions",
"BinLocationAttributes",
"BinLocationFields",
"BinLocations",
"BlanketAgreements",
"BOEDocumentTypes",
"BOEInstructions",
"BOEPortfolios",
"BPFiscalRegistryID",
"BPPriorities",
"Branches",
"BrazilBeverageIndexers",
"BrazilFuelIndexers",
"BrazilMultiIndexers",
"BrazilNumericIndexers",
"BrazilStringIndexers",
"BudgetDistributions",
"Budgets",
"BudgetScenarios",
"BusinessPartnerGroups",
"BusinessPartnerProperties",
"BusinessPartners",
"BusinessPlaces",
"CampaignResponseType",
"Campaigns",
"CashDiscounts",
"CashFlowLineItems",
"CertificateSeries",
"CESTCodes",
"ChartOfAccounts",
"ChecksforPayment",
"ChooseFromList",
"ClosingDateProcedure",
"Cockpits",
"CommissionGroups",
"Contacts",
"ContractTemplates",
"CorrectionInvoice",
"CorrectionInvoiceReversal",
"CorrectionPurchaseInvoice",
"CorrectionPurchaseInvoiceReversal",
"CostCenterTypes",
"CostElements",
"Counties",
"Countries",
"CreditCardPayments",
"CreditCards",
"CreditNotes",
"CreditPaymentMethods",
"Currencies",
"CustomerEquipmentCards",
"CustomsDeclaration",
"CustomsGroups",
"CycleCountDeterminations",
"DeductibleTaxes",
"DeductionTaxGroups",
"DeductionTaxHierarchies",
"DeductionTaxSubGroups",
"DeliveryNotes",
"Departments",
"Deposits",
"DepreciationAreas",
"DepreciationTypePools",
"DepreciationTypes",
"DeterminationCriterias",
"Dimensions",
"DistributionRules",
"DNFCodeSetup",
"DownPayments",
"Drafts",
"DunningLetters",
"DunningTerms",
"DynamicSystemStrings",
"ElectronicFileFormats",
"EmailGroups",
"EmployeeIDType",
"EmployeePosition",
"EmployeeRolesSetup",
"EmployeesInfo",
"EmployeeStatus",
"EmployeeTransfers",
"EmploymentCategorys",
"EnhancedDiscountGroups",
"ExceptionalEvents",
"ExtendedTranslations",
"FAAccountDeterminations",
"FactoringIndicators",
"FinancialYears",
"FiscalPrinter",
"FormattedSearches",
"FormPreferences",
"Forms1099",
"GLAccountAdvancedRules",
"GoodsReturnRequest",
"GovPayCodes",
"Holidays",
"HouseBankAccounts",
"IncomingPayments",
"IndiaHsn",
"Industries",
"IntegrationPackagesConfigure",
"IntrastatConfiguration",
"InventoryCountings",
"InventoryCycles",
"InventoryGenEntries",
"InventoryGenExits",
"InventoryOpeningBalances",
"InventoryPostings",
"InventoryTransferRequests",
"Invoices",
"ItemGroups",
"ItemProperties",
"Items",
"JournalEntries",
"JournalEntryDocumentTypes",
"KnowledgeBaseSolutions",
"KPIs",
"LandedCosts",
"LandedCostsCodes",
"LegalData",
"LengthMeasures",
"LocalEra",
"Manufacturers",
"MaterialGroups",
"MaterialRevaluation",
"Messages",
"MobileAddOnSetting",
"MultiLanguageTranslations",
"NatureOfAssessees",
"NCMCodesSetup",
"NFModels",
"NFTaxCategories",
"NotaFiscalCFOP",
"NotaFiscalCST",
"NotaFiscalUsage",
"OccurrenceCodes",
"Orders",
"PackagesTypes",
"PartnersSetups",
"PaymentBlocks",
"PaymentDrafts",
"PaymentReasonCodes",
"PaymentRunExport",
"PaymentTermsTypes",
"PickLists",
"POSDailySummary",
"PredefinedTexts",
"PriceLists",
"ProductionOrders",
"ProductTrees",
"ProfitCenters",
"ProjectManagements",
"ProjectManagementTimeSheet",
"Projects",
"PurchaseCreditNotes",
"PurchaseDeliveryNotes",
"PurchaseDownPayments",
"PurchaseInvoices",
"PurchaseOrders",
"PurchaseQuotations",
"PurchaseRequests",
"PurchaseReturns",
"PurchaseTaxInvoices",
"QueryAuthGroups",
"QueryCategories",
"Queue",
"Quotations",
"Relationships",
"ReportFilter",
"ReportTypes",
"ResourceCapacities",
"ResourceGroups",
"ResourceProperties",
"Resources",
"RetornoCodes",
"ReturnRequest",
"Returns",
"RouteStages",
"SalesForecast",
"SalesOpportunities",
"SalesOpportunityCompetitorsSetup",
"SalesOpportunityInterestsSetup",
"SalesOpportunityReasonsSetup",
"SalesOpportunitySourcesSetup",
"SalesPersons",
"SalesStages",
"SalesTaxAuthorities",
"SalesTaxAuthoritiesTypes",
"SalesTaxCodes",
"SalesTaxInvoices",
"Sections",
"SelfCreditMemos",
"SelfInvoices",
"SerialNumberDetails",
"ServiceCallOrigins",
"ServiceCallProblemSubTypes",
"ServiceCallProblemTypes",
"ServiceCalls",
"ServiceCallSolutionStatus",
"ServiceCallStatus",
"ServiceCallTypes",
"ServiceContracts",
"ServiceGroups",
"ShippingTypes",
"ShortLinkMappings(guid)",
"ShortLinkMappings",
"SpecialPrices",
"States",
"StockTakings",
"StockTransferDrafts",
"StockTransfers",
"TargetGroups",
"TaxCodeDeterminations",
"TaxCodeDeterminationsTCD",
"TaxInvoiceReport",
"TaxWebSites",
"Teams",
"TerminationReason",
"Territories",
"TrackingNotes",
"TransactionCodes",
"TransportationDocument",
"TSRExceptionalEvents",
"UnitOfMeasurementGroups",
"UnitOfMeasurements",
"UserDefaultGroups",
"UserFieldsMD",
"UserKeysMD",
"UserLanguages",
"UserObjectsMD",
"UserPermissionTree",
"UserQueries",
"Users",
"UserTablesMD",
"ValueMapping",
"ValueMappingCommunication",
"VatGroups",
"VendorPayments",
"WarehouseLocations",
"Warehouses",
"WarehouseSublevelCodes",
"WebClientBookmarkTiles",
"WebClientDashboards",
"WebClientFormSettings",
"WebClientLaunchpads",
"WebClientListviewFilters",
"WebClientNotifications",
"WebClientPreferences",
"WebClientRecentActivities",
"WebClientVariantGroups",
"WebClientVariants",
"WeightMeasures",
"WithholdingTaxCodes",
"WitholdingTaxDefinition",
"WizardPaymentMethods",
"WTaxTypeCodes"
]

def get_session():
    url = f"{SERVICE_LAYER_URL}/Login"
    payload = {"UserName": USER, "Password": PASS, "CompanyDB": "SBO_DEMO_SAPIENTIA"}
    response = requests.post(url, json=payload, verify=False)
    response.raise_for_status()
    return response.cookies

def login():
    url = "https://win-2p3p2clhj7s:50000/b1s/v1/Login"
    payload = {
        "CompanyDB": "SBO_DEMO_SAPIENTIA",       # ← reemplaza con tu base de datos
        "UserName": "manager",          # ← reemplaza con tu usuario
        "Password": "Pd121186A."              # ← reemplaza con tu contraseña
    }
    response = requests.post(url, json=payload, verify=False)
    response.raise_for_status()
    return response.cookies

def get_entities():
    return ENTITY_LIST

def extract_entities_from_edmx(edmx_xml: str):
    try:
        root = etree.fromstring(edmx_xml.encode())
        entities = root.xpath("//*[local-name()='EntityType']")
        return [e.attrib['Name'] for e in entities if 'Name' in e.attrib]
    except Exception as e:
        print(f"Error al parsear EDMX con lxml: {e}")
        return []

def get_entity_fields(entity_name):
    cookies = get_session()
    url = f"{SERVICE_LAYER_URL}/{entity_name}?$top=1"
    response = requests.get(url, cookies=cookies, verify=False)
    response.raise_for_status()
    data = response.json()
    if "value" in data and data["value"]:
        return list(data["value"][0].keys())
    return []